export const RESET_STORE = 'RESET_STORE';

export const SET_CONFIGS = 'SET_CONFIGS';

export const RESET_CONFIGS = 'RESET_CONFIGS';

export const SAVE_OPTIMIZATIONS = 'SAVE_OPTIMIZATIONS';

export const SAVE_REMARKS = 'SAVE_REMARKS';

export const UPDATE_REMARK = 'UPDATE_REMARK';

export const SAVE_SIDE_CHART = 'SAVE_SIDE_CHART';

export const UPDATE_PROGRESS = 'UPDATE_PROGRESS';

export const SAVE_PROCESS = 'SAVE_PROCESS';

export const RESET_PROCESS_PAGE = 'RESET_PROCESS_PAGE';

export const UPDATE_PROCESS_PAGE = 'UPDATE_PROCESS_PAGE';

export const SAVE_MESSAGE = 'SAVE_MESSAGE';

export const UPDATE_MESSAGE_PAGE = 'UPDATE_MESSAGE_PAGE';

export const INSERT_MESSAGE = 'INSERT_MESSAGE';
